<?php

/**
 * RokGallery_Model_Filters
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    RokGallery
 * @subpackage models
 * @author     RocketTheme LLC <support@rockettheme.com>
 * @version    SVN: $Id: Filters.php 10871 2013-05-30 04:06:26Z btowles $
 */
class RokGallery_Model_Filters extends RokGallery_Model_Base_Filters
{

}